### PR TITLE
Resource deletes should succeed on 404 and 403 responses

### LINKED ISSUE #32: Delete operations should treat 404 as success
While destroying resources, I received several 404 responses because I manually deleted the resources outside of Terraform.

* Error: Not found (I don't know which resource produced this error)
* Error: Error deleting IP reservation block ...: DELETE https://api.equinix.com/metal/v1/ips/...: 404 Not found 
* Error: DELETE https://api.equinix.com/metal/v1/bgp/sessions/...: 404 Not found 

404 responses on delete requests should be treated as successful deletions.

### LINKED ISSUE #42: Unassign vlan 422s are not errors
When unassigning a VLAN, a POST 422 "not assigned" message should not be handled as an error. This is equivalent to a DELETE command returning a 404 on other resources.

```
Error: POST https://api.equinix.com/metal/v1/ports/a213bf05-d63d-457e-9e1d-ed201e9b12f9/unassign: 422 Virtual network 1300 not assigned 
```

Similarly, a 403 represents a port that is not associated with an active device. This can also be considered a successful unassignment.

```
Error: POST https://api.equinix.com/metal/v1/ports/a213bf05-d63d-457e-9e1d-ed201e9b12f9/unassign: 403 You are not authorized to view this resource 
```

### LINKED ISSUE #43: 404 should not error when deleting IP reservations
Deleting an IP reservation that was removed should not be an error:
```
Error: Error deleting IP reservation block 079e8000-da9f-417c-8953-ffb8facd8f3f: DELETE https://api.equinix.com/metal/v1/ips/079e8000-da9f-417c-8953-ffb8facd8f3f: 404 Not found 
```

### PR DESCRIPTION
**Pull request by displague**
Fixes #42 
Fixes #43 
Fixes #32

### CODE REVIEW

**Comment by displague** [comment]
Test results look good, compared to past runs.

We have a stray line of debugging to remove:
```
key: packngo.SSHKey{ID:"e2ce7a4d-4dd1-407e-9293-3214a958c253", Label:"tfacc-project-key-test", Key:"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQDKt0TrcQXNhk9ocaSp6L2HWzjG6ltyx9euZ72gRa7on/ne5Q9lr0btU3A6igewZBqd+wxOqdKw4SNHmTI7ixGdmQrtGKjp9y9OVMkqM6gABtJ78YrUjddT3hUKB+TnAiphGmNl086SHSwjhHihFEdSSyBjXxRGXjCVFiSflJx/IQ== ", FingerPrint:"5b:b0:f5:a6:2a:c8:c3:2e:39:51:1f:a5:3f:30:39:9f", Created:"2021-03-16T05:28:05Z", Updated:"2021-03-16T05:28:06Z", Owner:packngo.Href{Href:"/metal/v1/projects/8e479464-1417-42e2-a1b4-8d7876c23326"}, URL:"/metal/v1/ssh-keys/e2ce7a4d-4dd1-407e-9293-3214a958c253"}2021/03/16 05:30:08 [DEBUG] GET https://api.equinix.com/metal/v1/projects/8e479464-1417-42e2-a1b4-8d7876c23326
```

There are also a number of `Error: Not Found` messages from BGP tests. I'm wondering if I introduced that with these changes.

I'll see if I can get these sorted in this PR.

One other test failure that came up was #24, I'll take a look in this PR.

**Comment by t0mk** [comment]
hi @displague, as for the action of removal, the Equinux Metal API returns `HTTP 204 No Content` on DELETEs of resources. If the API returns 4xx there should be some problem.

I will take a deeper look on this PR now.

**Comment by t0mk** [comment]
It seems that checking for 404s on delete is common practice:
* https://github.com/scaleway/terraform-provider-scaleway/blob/master/scaleway/resource_instance_server.go#L714
* https://github.com/digitalocean/terraform-provider-digitalocean/blob/main/digitalocean/resource_digitalocean_droplet.go#L635

**Comment by displague** [comment]
- 2xx (specifically 204, as documented) is a successful delete of a resource that exists.
- 404 is a successful delete of a resource that was already deleted.
- 403 is a successful delete of some portable resources that reassigned, deleted, or removed (at least in the EM API). Arguably, some of these would make more sense as 404s.
  - resources with have persistent ids, regardless of user (ports)
  - devices that failed to provision
  - other cases

403 A resource that was deleted outside of Terraform, or as a side-effect, or in

**Comment by t0mk** [comment]
It seems to fix the vlan assignment errors and the ip reservation errors. There are still errors when setting BGP for a project, but that can be solved elsewhere I think.

I wonder what's the error in project import test. But that's also beyond the scope of this PR, so LGTM.

**Review by t0mk — APPROVED** [review]

**Comment by displague** [comment]
Noting that the `filepath` to `path` change in https://github.com/equinix/terraform-provider-metal/pull/44/commits/e399bbbbc6e2bc8861ec826259810601bfc60dd6 is trivial - the important change there is a fix for how the project id is detected in project hrefs.  The previous code expected the first 10 characters to be `/projects/` which is no longer the case.

**Pull request merged**
